version: '3.4'

services:
  web:
    build: 
      context: .
      target: build-stage
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 80:80
    environment: 
      env_file: .env
    command: 
      - /bin/sh
      - -c
      - |
        yarn
        yarn dev

volumes:
  node_modules:
