version: '3.4'

services:

  web:
    build: 
      context: ./packages/client
      target: build-stage
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 80:80
    environment: 
      env_file: .env
    command: 
      - /bin/sh
      - -c
      - |
        cd ./packages/client
        yarn
        yarn dev

  api:
    build: 
      context: ./packages/server
    ports:
      - '3030:3030'
    volumes:
      - .:/code
      - /code/node_modules
    command: 
      - /bin/sh
      - -c
      - |
        cd ./packages/server
        yarn
        yarn dev
    links:
      - db
    depends_on:
      - db

  db:
    image: 'mongo:3.4'
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  node_modules:
  mongo_data:
